version: '3.7'

services:

  mongo:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    env_file: .env
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    build:
      context: .
      dockerfile: docker/mongo-express/Dockerfile
    env_file: .env
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
