// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type Node interface {
	IsNode()
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type Todo struct {
	ID       string `json:"id"`
	Text     string `json:"text"`
	Complete bool   `json:"complete"`
}

func (Todo) IsNode() {}

type TodoConnection struct {
	PageInfo PageInfo    `json:"pageInfo"`
	Edges    []*TodoEdge `json:"edges"`
}

type TodoEdge struct {
	Node   *Todo  `json:"node"`
	Cursor string `json:"cursor"`
}

type User struct {
	ID             string          `json:"id"`
	Todos          *TodoConnection `json:"todos"`
	TotalCount     int             `json:"totalCount"`
	CompletedCount int             `json:"completedCount"`
}

func (User) IsNode() {}
