// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dataloader

type Node interface {
	IsNode()
}

type OrderConnection struct {
	PageInfo *PageInfo    `json:"pageInfo"`
	Edges    []*OrderEdge `json:"edges"`
}

type OrderEdge struct {
	Node   *Order `json:"node"`
	Cursor string `json:"cursor"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}
